"""Waymo Open Motion Dataset Metrics for PyTorch."""

from womd_torch_metrics.motion_metrics import (
    compute_motion_metrics,
    MotionMetricsConfig,
    StepConfig,
    compute_min_ade,
    compute_min_fde,
    compute_miss_rate,
    compute_overlap_rate,
    compute_map_metric,
    classify_trajectory_type,
    compute_precision_recall,
    compute_average_precision,
    compute_speed,
    compute_speed_scale,
    TYPE_UNSET,
    TYPE_VEHICLE,
    TYPE_PEDESTRIAN,
    TYPE_CYCLIST,
    TYPE_OTHER,
    TRAJECTORY_TYPE_STATIONARY,
    TRAJECTORY_TYPE_STRAIGHT,
    TRAJECTORY_TYPE_STRAIGHT_LEFT,
    TRAJECTORY_TYPE_STRAIGHT_RIGHT,
    TRAJECTORY_TYPE_LEFT_U_TURN,
    TRAJECTORY_TYPE_LEFT_TURN,
    TRAJECTORY_TYPE_RIGHT_U_TURN,
    TRAJECTORY_TYPE_RIGHT_TURN,
)

from womd_torch_metrics.map_metrics import (
    compute_map_metrics,
    compute_distance_to_road_edge,
    compute_offroad_rate,
    compute_bounding_box_corners,
    compute_signed_distance_to_polylines,
    OFFROAD_DISTANCE_THRESHOLD,
)

__version__ = "0.1.0"
__all__ = [
    "compute_motion_metrics",
    "MotionMetricsConfig",
    "StepConfig",
    "compute_min_ade",
    "compute_min_fde",
    "compute_miss_rate",
    "compute_overlap_rate",
    "compute_map_metric",
    "classify_trajectory_type",
    "compute_precision_recall",
    "compute_average_precision",
    "compute_speed",
    "compute_speed_scale",
    "TYPE_UNSET",
    "TYPE_VEHICLE",
    "TYPE_PEDESTRIAN",
    "TYPE_CYCLIST",
    "TYPE_OTHER",
    "TRAJECTORY_TYPE_STATIONARY",
    "TRAJECTORY_TYPE_STRAIGHT",
    "TRAJECTORY_TYPE_STRAIGHT_LEFT",
    "TRAJECTORY_TYPE_STRAIGHT_RIGHT",
    "TRAJECTORY_TYPE_LEFT_U_TURN",
    "TRAJECTORY_TYPE_LEFT_TURN",
    "TRAJECTORY_TYPE_RIGHT_U_TURN",
    "TRAJECTORY_TYPE_RIGHT_TURN",
    # Map metrics
    "compute_map_metrics",
    "compute_distance_to_road_edge",
    "compute_offroad_rate",
    "compute_bounding_box_corners",
    "compute_signed_distance_to_polylines",
    "OFFROAD_DISTANCE_THRESHOLD",
]
